version: '3.8'

services:
  backend:
    image: ghcr.io/juanchi0207/coldmsg-back:dev   # cambia “main” por “dev” si quieres la versión dev
    container_name: coldmsg-back
    restart: unless-stopped
    ports:
      - '8080:8080'
    networks:
      - coldmsg-net

  frontend:
    image: ghcr.io/juanchi0207/coldmsg-front:dev  # idem, usa “dev” si corresponde
    container_name: coldmsg-front
    restart: unless-stopped
    ports:
      - '80:80'
    networks:
      - coldmsg-net

networks:
  coldmsg-net:
    driver: bridge
