name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          # etiqueta con rama (main o dev)
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          # pasa la URL de API desde los secrets
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}
