name: Build and Push Docker Image

on:
  push:
    branches: [main, dev]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (needed for Docker build context)
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} \
            -t ghcr.io/${{ secrets.GHCR_USERNAME }}/coldmsg-front:latest \
            -t ghcr.io/${{ secrets.GHCR_USERNAME }}/coldmsg-front:${{ github.ref_name }} \
            .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/coldmsg-front:latest
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/coldmsg-front:${{ github.ref_name }}
